[package]
name = "dateg"
version = "0.1.0"
edition = "2024"

[dependencies]
dateg_macro.path = "../dateg_macro"
egglog-bridge = { git = "https://github.com/egraphs-good/egglog.git", rev = "8879605cafad303db25787406163a7e5bc845f5d" }
egglog-core-relations = { git = "https://github.com/egraphs-good/egglog.git", rev = "8879605cafad303db25787406163a7e5bc845f5d" }
egglog-numeric-id = { git = "https://github.com/egraphs-good/egglog.git", rev = "8879605cafad303db25787406163a7e5bc845f5d" }
indexmap.workspace = true
ahash.workspace = true
paste.workspace = true
