[workspace]
resolver = "3"

members = ["crates/*"]

[workspace.dependencies]
indexmap = "2.14.0"
anyhow = "1.0.103"
log = "0.4.33"
env_logger = "0.11.11"
ahash = "0.8.12"
paste = "1.0.15"
proc-macro2 = "1.0.106"
syn = "2.0.118"
quote = "1.0.46"
easy-smt = "0.3.2"

[profile.work]
inherits = "dev"
opt-level = 2

[profile.optimize]
inherits = "release"
lto = "thin"
